version: '3.7'

# -------------- Edit .env and Here ---------------
x-var: &REQUIRE_IP
    ## IP or network addresses to be accessed from.
    ## NOTE: docker-compose default network assigns, with round robin,
    ##       172.18-31.0.0/16 or 192.168.x.0/20 in 0.0.16.0 step
    ##       to its default bridge network.
    ## For docker-compose default network:
    # "172 192.168"
    # "172.0.0.0\\\/11 192.168"
    10.0.0.1
# ---------------------------------

services:
    fswiki_local:
        container_name: fswiki_${FSWIKI_PLATFORM}_local_dc_${FSWIKI_VERSION}
        image: fswiki_${FSWIKI_PLATFORM}_local_dc:${FSWIKI_VERSION}
        build:
            context: .
            dockerfile: "./${FSWIKI_PLATFORM}/Dockerfile"
            args:
                require_ip: *REQUIRE_IP
                tag_version: ${TAG_VERSION}
                fswiki_version: ${FSWIKI_VERSION}
                fswiki_tmp_dir: ${FSWIKI_TMP_DIR}
        volumes:
            # Adding "" does not work.
            - ${FSWIKI_DATA_ROOT}/data:/usr/local/apache2/htdocs/data
            - ${FSWIKI_DATA_ROOT}/attach:/usr/local/apache2/htdocs/attach
            - ${FSWIKI_DATA_ROOT}/config:/usr/local/apache2/htdocs/config
            - ${FSWIKI_DATA_ROOT}/log:/usr/local/apache2/htdocs/log
            - ${FSWIKI_DATA_ROOT}/theme:/usr/local/apache2/htdocs/theme
        ports:
            - "${FSWIKI_PORT}:80"
        restart: always
        networks:
            "10_0_0":
                ipv4_address: 10.0.0.2

    fswiki_private:
        container_name: fswiki_${FSWIKI_PLATFORM}_private_dc_${FSWIKI_VERSION}
        image: fswiki_${FSWIKI_PLATFORM}_local_dc:${FSWIKI_VERSION}
        build:
            context: .
            dockerfile: "./${FSWIKI_PLATFORM}/Dockerfile"
            args:
                require_ip: *REQUIRE_IP
                tag_version: ${TAG_VERSION}
                fswiki_version: ${FSWIKI_VERSION}
                fswiki_tmp_dir: ${FSWIKI_TMP_DIR}
        volumes:
            # Adding "" does not work.
            - C:/Users/kaz/private/wiki_private/data:/usr/local/apache2/htdocs/data
            - C:/Users/kaz/private/wiki_private/attach:/usr/local/apache2/htdocs/attach
            - C:/Users/kaz/private/wiki_private/config:/usr/local/apache2/htdocs/config
            - C:/Users/kaz/private/wiki_private/log:/usr/local/apache2/htdocs/log
            - C:/Users/kaz/private/wiki_private/theme:/usr/local/apache2/htdocs/theme
        ports:
            - "127.0.0.1:9366:80"
        restart: always
        networks:
            "10_0_0":
                ipv4_address: 10.0.0.3

networks:
    "10_0_0":
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
